apiVersion: skaffold/v2beta11
kind: Config
deploy:
  kubectl:
    manifests: ["k8s/*.yaml", "k8s/dev/*.yaml", "k8s/dev/secrets/*.yaml"]
build:
  artifacts:
    - image: peterulb/spending-worker
      jib:
        args: ["-DskipTests"]