kind: ConfigMap
apiVersion: v1
metadata:
  name: spending-worker
data:
  application.properties: |-
    server.port=8080
    app.gcp.subscription-name=add-spending-v1-worker
    logging.level.root=INFO
    spring.datasource.url=jdbc:postgresql://postgres-service:5432/spending-db
    spring.cloud.kubernetes.reload.enabled=true
    spring.cloud.gcp.credentials.location=file:/etc/secrets/google/key.json
    spring.jpa.hibernate.ddl-auto=update
  application-dev.properties: |-
    spring.profiles=dev
    server.error.include-stacktrace=always
  application-prod.properties: |-
    spring.profiles=prod
    server.error.include-stacktrace=never
    logging.level.root=ERROR
    spring.devtools.add-properties=false
    spring.jpa.hibernate.ddl-auto=validate